commit
mate-academy/js_stateful-object pull request #1048
Opened 2022-03-29 11:50 UTC by VladSkoromnyi

2022-03-31 10:17 UTC, vlasiuk-anatolii approved these changes
Ок!

2022-03-31 10:17 UTC, vlasiuk-anatolii commented on src/transformState.js
> +    } else if (actions[i].type === 'removeProperties') {
запис else можна опустити. Наступний if запистувати з нового рядка.

2022-03-31 10:17 UTC, vlasiuk-anatolii commented on src/transformState.js
> +      }
Можна застосувати switch

2022-03-31 13:20 UTC, Anna-Tkachenko requested changes
Will be better to use switch / case if we need to do some logic depending on value of some variable

2022-04-01 08:19 UTC, Anna-Tkachenko approved these changes
Good job!
Don't forget to add default case for switch / case statement

2024-08-13 09:16 UTC, closed without merging