too dificult, perhaps my solution not one of the simplest
mate-academy/js_stateful-object pull request #1124
Opened 2022-04-26 11:22 UTC by ZUBOV-ILLIA

2022-04-26 16:17 UTC, EnjSadman approved these changes

2022-04-26 17:50 UTC, Denchepornyuk requested changes

2022-04-26 17:50 UTC, Denchepornyuk commented on src/transformState.js
> +  }
use `switch case` instead of `if`

2022-04-26 17:50 UTC, Denchepornyuk commented on src/transformState.js
> +        }
you don't need two loops here
make one loop for `obj.keysToRemove` and delete every key from `state` witch presented in `obj.keysToRemove`


also, you don't need `if`
If key doesn't exist in object and you are trying to remove this key, JS will skip it without any error
<img width="225" alt="Screenshot 2022-04-26 at 20 48 35" src="https://user-images.githubusercontent.com/37452763/165361353-ab345f77-fa02-40f4-8a3f-1d2a34e9ae3d.png">

2022-04-27 11:58 UTC, Denchepornyuk approved these changes

2025-03-07 09:10 UTC, closed without merging