solution added
mate-academy/js_stateful-object pull request #1174
Opened 2022-05-11 11:12 UTC by kostya-konev

2022-05-11 14:44 UTC, ArturErmolenko requested changes
Better use switch case

2022-05-12 12:33 UTC, marina-tilniak requested changes

2022-05-12 12:33 UTC, marina-tilniak commented on src/transformState.js
> +    switch (action['type']) {
```suggestion
    switch (action.type) {
```

2022-05-12 12:33 UTC, marina-tilniak commented on src/transformState.js
> +          }
тут не потрібно перевіряти чи є такий ключ у state, бо якщо такого елемента нема, то delete просто не спрацює, тож другий цикл можна забрати

2022-05-12 12:33 UTC, marina-tilniak commented on src/transformState.js
> +    switch (action['type']) {
коли ми звертаємося до ключа по його назві(без змінної) то використовуємо крапку

2022-05-13 07:29 UTC, marina-tilniak approved these changes
👍

2022-05-16 07:42 UTC, ArtemTopolskyi approved these changes

2023-09-12 13:36 UTC, closed without merging