Develop
mate-academy/js_stateful-object pull request #1471
Opened 2022-08-24 14:28 UTC by NazikVr

2022-08-29 06:12 UTC, stanislav-topikha requested changes
comments ⬇️

2022-08-29 06:12 UTC, stanislav-topikha commented on src/transformState.js
> +          delete state[`${key}`];
??
```suggestion
          delete state[key];
```

2022-08-29 06:12 UTC, stanislav-topikha commented on src/transformState.js
> +          delete state[`${x}`];
```suggestion
          delete state[key];
```

2022-08-29 06:12 UTC, stanislav-topikha commented on src/transformState.js
> +    switch (actions[i].type) {
use `for of `
or 
`const action = actions[i];`

2022-09-01 15:56 UTC, marina-tilniak approved these changes

2022-09-01 15:56 UTC, marina-tilniak commented on src/transformState.js
> +        action.keysToRemove.forEach((x) => {
```suggestion
        action.keysToRemove.forEach((key) => {
```

2025-10-08 16:34 UTC, closed without merging