Transforming state
mate-academy/js_stateful-object pull request #1526
Opened 2022-09-12 16:58 UTC by Vladosik1337

2022-09-12 17:56 UTC, glugovsky commented on src/transformState.js
> +    }
switch/case should always have default case for error handling
```suggestion
    default:
        throw new Error('Wrong type!');
    }
```

2022-09-13 06:21 UTC, glugovsky approved these changes
GJ!

2022-09-14 07:29 UTC, naziamoff requested changes

2022-09-14 07:29 UTC, naziamoff commented on src/transformState.js
> +        for (const deleteValue of keysToRemove) {
This would make your code clearer
```suggestion
        for (const keyToRemove of keysToRemove) {
```

2022-09-14 07:29 UTC, naziamoff commented on src/transformState.js
> +        for (const deleteAll in state) {
delete all would be a good name for a function, but not for a variable.
It has to be a noun and it should describe what is stored inside

2022-09-14 08:24 UTC, naziamoff approved these changes
GJ!

2025-11-08 12:41 UTC, closed without merging