solution
mate-academy/js_stateful-object pull request #1649
Opened 2022-10-19 16:58 UTC by mitattt

2022-10-19 18:05 UTC, masha-girya approved these changes
Great job!!

2022-10-21 06:36 UTC, Olexandr6 requested changes
Your solution is good but not great🙂

2022-10-21 06:36 UTC, Olexandr6 commented on src/transformState.js
> +        for (const keyRemove of action.keysToRemove) {
```suggestion
        for (const keyToRemove of action.keysToRemove) {
```

2022-10-21 06:36 UTC, Olexandr6 commented on src/transformState.js
> +    }
Let's throw an error here instead.
Read more - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw

2022-10-21 07:01 UTC, Olexandr6 approved these changes

2022-10-21 07:01 UTC, Olexandr6 commented on src/transformState.js
> +        throw new Error('Error');
This error isn't informative

2025-01-16 21:10 UTC, closed without merging