solution
mate-academy/js_stateful-object pull request #1719
Opened 2022-11-13 10:14 UTC by olenitut

2022-11-15 07:22 UTC, Bohdan-Maksymiuk requested changes
try to use `switch case` for such predefined cases

2022-11-15 07:22 UTC, Bohdan-Maksymiuk commented on src/transformState.js
> +  });
avoid such nesting `else if` conditions
This code is hard to read and maintain

2022-11-15 12:30 UTC, Bohdan-Maksymiuk requested changes

2022-11-15 12:30 UTC, Bohdan-Maksymiuk commented on src/transformState.js
> +    }
believe that it should be default behaviour
what if someone will pass invalid data - state will be cleared by default
[usefulLink](https://www.quora.com/What-is-the-purpose-of-default-in-a-switch-case)
[usefulLink](https://softwareengineering.stackexchange.com/questions/181459/is-it-necessary-to-add-the-default-case-while-using-switch-cases)

2022-11-16 16:25 UTC, Viktor-Kost requested changes
UPD:
Have given a recommendation

2022-11-16 16:25 UTC, Viktor-Kost commented on src/transformState.js
> +    }
You would better use `default` for switch statement. Cause what will happen if we pass a case we don't have?
For example for default you can throw an error `throw new Error('invalid type of action')`

2022-11-16 16:51 UTC, Viktor-Kost approved these changes
Well done!

2023-10-18 14:11 UTC, closed without merging