Finish
mate-academy/js_stateful-object pull request #2077
Opened 2023-02-19 23:34 UTC by Ultramarin

Solution for task stateful-object

2023-02-20 11:16 UTC, VitaliyBondarenko1982 requested changes
Good job, but needs some refactor

2023-02-20 11:16 UTC, VitaliyBondarenko1982 commented on src/transformState.js
> +  }
Better to use switch...case

2023-02-20 11:16 UTC, VitaliyBondarenko1982 commented on src/transformState.js
> +      });
```suggestion
    Object.assign(state, extraData);
```

2023-02-20 11:16 UTC, VitaliyBondarenko1982 commented on src/transformState.js
> +  for (const action of actions) {
```suggestion
  for (const action of actions) {
  const { type, extraData, keysToRemove } = action
```

2023-02-20 11:16 UTC, VitaliyBondarenko1982 commented on src/transformState.js
> +      action['keysToRemove'].forEach(key => {
```suggestion
      keysToRemove.forEach(key => {
```

2023-02-20 11:16 UTC, VitaliyBondarenko1982 commented on src/transformState.js
> +      });
```suggestion
       for (const key in state) {
          delete state[key];
        }
```

2023-02-22 19:55 UTC, Ultramarin commented on src/transformState.js
> +  }
I change if to wsitch

2023-02-22 19:56 UTC, Ultramarin commented on src/transformState.js
> +  for (const action of actions) {
Change

2023-02-22 19:56 UTC, Ultramarin commented on src/transformState.js
> +      });
Change

2023-02-22 19:56 UTC, Ultramarin commented on src/transformState.js
> +      action['keysToRemove'].forEach(key => {
I change

2023-02-22 19:56 UTC, Ultramarin commented on src/transformState.js
> +      });
I change change

2023-02-23 08:28 UTC, tetiana-ivanchenko requested changes
![image](https://user-images.githubusercontent.com/59209337/220856192-4be906b9-70bc-451c-901e-f1c8d276f274.png)

2023-07-02 20:33 UTC, Ultramarin commented
> ![image](https://user-images.githubusercontent.com/59209337/220856192-4be906b9-70bc-451c-901e-f1c8d276f274.png)

I fix this

2023-07-02 20:33 UTC, closed without merging