one commit
mate-academy/js_stateful-object pull request #221
Opened 2020-08-04 12:33 UTC by zarva6596

2020-08-04 15:30 UTC, DolgKreker requested changes

2020-08-04 15:30 UTC, DolgKreker commented on src/transformState.js
> +  for (let i = 0; i < transforms.length; i++) {
```suggestion
  for (const transform of transforms) {
```

2020-08-04 15:30 UTC, DolgKreker commented on src/transformState.js
> +      for (const key in transforms[i].properties) {
```suggestion
      for (const key in transform.properties) {
```

2020-08-04 15:30 UTC, DolgKreker commented on src/transformState.js
> +    if (transforms[i].operation === 'addProperties') {
Перероби з if else на switch case

2020-08-06 08:42 UTC, DolgKreker approved these changes

2020-08-06 14:42 UTC, vkryvytskyi approved these changes

2020-08-06 14:42 UTC, vkryvytskyy commented on src/transformState.js
> +        }
```suggestion
        for (const key of transform.properties) {
          delete state[key];
        }
```

2024-07-03 16:30 UTC, closed without merging