done
mate-academy/js_stateful-object pull request #2255
Opened 2023-04-10 14:46 UTC by maxonshev

2023-04-10 16:53 UTC, etojeDenys requested changes

2023-04-10 16:53 UTC, etojeDenys commented on src/transformState.js
> +      }
better to rewrite it using switch\case instead of if`s, it will improve readability a lot

2023-04-10 18:51 UTC, loralevitska requested changes
Almost perfect) Let's improve

2023-04-10 18:51 UTC, loralevitska commented on src/transformState.js
> +// function transformState(state, actions) {
Remove comments

2023-04-10 18:51 UTC, loralevitska commented on src/transformState.js
> +  for (const action of actions) {
Destructure `action`
```suggestion
  for (const { type, extraData, keysToRemove } of actions) {
```

2023-04-11 06:56 UTC, etojeDenys approved these changes
lgtm

2025-03-07 10:49 UTC, closed without merging