add transformState solution
mate-academy/js_stateful-object pull request #2300
Opened 2023-05-01 19:14 UTC by DidenkoDenis306

2023-05-08 10:47 UTC, 33Orange requested changes
The code works, but does not match several items in the checklist.

2023-05-08 10:47 UTC, 33Orange commented on src/transformState.js
> +        for (const key of action.keysToRemove) {
Use array methods here instead nested loop. `Nested loops === EVIL`

2023-05-08 10:47 UTC, 33Orange commented on src/transformState.js
> +        return null;
[CODE STYLE]: switch/case should always have default case for error handling.

2023-05-11 11:03 UTC, Anna-Tkachenko approved these changes
⭐️

2024-07-09 10:18 UTC, closed without merging