Latest solution
mate-academy/js_stateful-object pull request #2357
Opened 2023-05-10 15:24 UTC by PanyaPrimal

2023-05-12 06:41 UTC, dinaminahi requested changes

2023-05-12 06:41 UTC, dinaminahi commented on src/transformState.js
> +        }
Better here would be to use Object.assign or spread operator, which is easier and more readable

2023-05-12 06:41 UTC, dinaminahi commented on src/transformState.js
> +    const { type } = action;
Let`s extract all data we need at once

2023-05-12 06:41 UTC, dinaminahi commented on src/transformState.js
> +        }
it's better to create separate function for this, so our `switch-case` would e smaller and more readable

2023-05-12 06:41 UTC, dinaminahi commented on src/transformState.js
> +        }
same here

2023-05-15 07:45 UTC, naziamoff approved these changes
great job 🔥

2023-05-15 07:45 UTC, naziamoff commented on src/transformState.js
> +  }
I guess you can just reset the object instead of removing properties one by one

2025-12-18 12:06 UTC, closed without merging