add solution
mate-academy/js_stateful-object pull request #2365
Opened 2023-05-10 21:07 UTC by vitvadym

2023-05-11 15:06 UTC, silchyn approved these changes

2023-05-11 15:07 UTC, silchyn requested changes
checklist rule `#4`

2023-05-12 07:55 UTC, 33Orange requested changes
Good job.

A few moments to fix

2023-05-12 07:55 UTC, 33Orange commented on src/transformState.js
> +  const currentState = state;
It is unnecessary to create a new variable 'currentState'. You can directly modify 'state' without creating a new reference.

2023-05-12 07:55 UTC, 33Orange commented on src/transformState.js
> +  return state;
Returning 'state' is not necessary, as the function is supposed to modify the original object. Remove the 'return' statement.

2023-05-12 07:55 UTC, 33Orange commented on src/transformState.js
> +        };
Let's move this code into a separate function after `transformState`

2023-05-12 07:55 UTC, 33Orange commented on src/transformState.js
> +        }
Let's move this code into a separate function after `transformState`

2023-05-15 07:29 UTC, naziamoff approved these changes
great job 👍 
If we create a helper function - we usually move it to a separate file. You can practice this if you want

2024-06-25 19:44 UTC, silchyn approved these changes

2024-11-22 21:06 UTC, closed without merging