add task solution
mate-academy/js_stateful-object pull request #2479
Opened 2023-06-13 13:44 UTC by ivankovbohdan

2023-06-14 06:46 UTC, tetiana-ivanchenko requested changes

2023-06-14 06:46 UTC, tetiana-ivanchenko commented on src/transformState.js
> +    const { type } = action;
add here all properties instead of using destructuring assignment in the each case

2023-06-14 06:46 UTC, tetiana-ivanchenko commented on src/transformState.js
> +      case 'removeProperties':
```suggestion
        break;
        
      case 'removeProperties':
```

2023-06-15 06:00 UTC, anstsot approved these changes

2023-12-07 10:07 UTC, closed without merging