Solution
mate-academy/js_stateful-object pull request #2506
Opened 2023-06-20 15:31 UTC by YuriyBilskiy

2023-06-20 17:27 UTC, loralevitska requested changes
Almost done) Let's improve

2023-06-20 17:27 UTC, loralevitska commented on src/transformState.js
> +  for (const action of actions) {
Destructure values from `action`

2023-06-20 17:27 UTC, loralevitska commented on src/transformState.js
> +      }
Use [`switch case`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch) in cases where you constantly compare one value with others

2023-06-21 15:43 UTC, sTorba24 approved these changes
GJ 🚀

2023-06-21 15:43 UTC, sTorba24 commented on src/transformState.js
> +    const { type, extraData, keysToRemove } = action;
you can do it directly in loop like 

const { type, extraData, keysToRemove } of actions

2024-08-07 16:23 UTC, closed without merging