done
mate-academy/js_stateful-object pull request #254
Opened 2020-09-21 14:50 UTC by aionova

2020-09-21 16:01 UTC, yazheviks approved these changes
Looking nice!)

2020-09-22 13:36 UTC, solaryasha requested changes

2020-09-22 13:36 UTC, solaryasha commented on src/transformState.js
> +      }
`switch` інструкція тут підходить краще

2020-09-22 13:36 UTC, solaryasha commented on src/transformState.js
> +      Object.assign(state, elem.properties);
Використай тут spread оператор

2020-09-22 13:36 UTC, solaryasha commented on src/transformState.js
> +      for (let i = 0; i < elem.properties.length; i++) {
Застосуй тут `for in ` цикл

2020-09-22 13:39 UTC, solaryasha commented on src/transformState.js
> +  for (const elem of transforms) {
```suggestion
  for (const transform of transforms) {
```

2020-09-22 14:46 UTC, solaryasha approved these changes

2023-09-27 09:02 UTC, closed without merging