solution
mate-academy/js_stateful-object pull request #2682
Opened 2023-08-03 15:18 UTC by vladyslav-svorin

2023-08-03 15:35 UTC, loralevitska requested changes
Good job! There are things that should be fixed:

2023-08-03 15:35 UTC, loralevitska commented on src/transformState.js
> +        if (actions[i].keysToRemove !== undefined) {
There's no need for checking if 'keysToRemove' is undefined. If it's undefined, the later for loop just won't execute.

2023-08-03 15:35 UTC, loralevitska commented on src/transformState.js
> +    const mainAction = actions[i].type;
Instead of traditional for loop, use of 'for...of' loop is recommended for better readability when iterating over an array.

2023-08-03 15:35 UTC, loralevitska commented on src/transformState.js
> +    const mainAction = actions[i].type;
Destructure action
`const { type, extraData, keysToRemove } = actions[i]`

2023-08-03 17:47 UTC, VitaliyBodnar requested changes
Almost done!

2023-08-03 17:47 UTC, VitaliyBodnar commented on src/transformState.js
> +        const toRemove = keysToRemove;
this variable is reduntant here

2023-08-03 17:47 UTC, VitaliyBodnar commented on src/transformState.js
> +        }
don't see any sense in using  for loop, better to use` for of` or `forEach` here

2023-08-04 06:06 UTC, polosanya requested changes
One small but important fix left 🙏

2023-08-04 06:06 UTC, polosanya commented on src/transformState.js
> +    }
![image](https://github.com/mate-academy/js_stateful-object/assets/96409563/194b5345-1536-4ec6-b643-2a0d1e084970)

2023-08-04 11:30 UTC, OleziO requested changes

2023-08-04 11:30 UTC, OleziO commented on src/transformState.js
> +      case 'clear':
Move all cases to the object.

Example of usage:
  `case ActionType.Clear:`

2023-08-04 14:53 UTC, VitaliyBodnar requested changes
Good job!

2023-08-04 14:56 UTC, VitaliyBodnar approved these changes

2026-05-16 08:56 UTC, closed without merging