add task solution
mate-academy/js_stateful-object pull request #2718
Opened 2023-08-15 12:05 UTC by MishaLehotskyi

2023-08-15 16:16 UTC, Andriy-Shymkiv requested changes

2023-08-15 16:16 UTC, Andriy-Shymkiv commented on src/transformState.js
> +  const CLEAR_PROPERTIES = 'clear';
why you hard coded all this type's instead of using switch case?

2023-08-15 16:16 UTC, Andriy-Shymkiv commented on src/transformState.js
> +  const CLEAR_PROPERTIES = 'clear';
[checklist](https://github.com/mate-academy/js_stateful-object/blob/master/checklist.md) rule 2

2023-08-15 16:16 UTC, Andriy-Shymkiv commented on src/transformState.js
> +      for (const remove of action.keysToRemove) {
```suggestion
      for (const key of action.keysToRemove) {
```

2023-08-17 11:37 UTC, xiimiik approved these changes
Nice work!

2024-06-26 19:36 UTC, closed without merging