Solution
mate-academy/js_stateful-object pull request #341
Opened 2020-12-10 13:32 UTC by Layrovell

2020-12-10 18:15 UTC, dtsehelnyk approved these changes
хорошая работа)

2020-12-11 08:34 UTC, varseniuk requested changes
Always try to add the 'default' case for 'switch...case' statements

2020-12-11 08:34 UTC, varseniuk commented on src/transformState.js
> +        for (const i in state) {
```suggestion
        for (const property of key.properties) {
          delete state[property];
        }
        break;

      case 'clear':
        for (const value in state) {
```

try to use more meaningful names for variables

2020-12-11 08:34 UTC, varseniuk commented on src/transformState.js
> +    }
Add 'default' case

2020-12-11 15:19 UTC, varseniuk approved these changes
On 'default case' you can log smth to console (like 'Error! Unknown type of data!').
Or just 'break' and stop the function

2024-05-02 16:20 UTC, closed without merging