js_stateful-object
mate-academy/js_stateful-object pull request #407
Opened 2021-02-10 11:35 UTC by SofiiaAsieieva

2021-02-10 11:57 UTC, Cheliojul approved these changes
well done

2021-02-10 16:54 UTC, solaryasha requested changes

2021-02-10 16:54 UTC, solaryasha commented on src/transformState.js
> +        for (const property in transform.properties) {
transform.properties - це масив, тому використай `for of`

2021-02-11 08:07 UTC, solaryasha approved these changes

2026-02-02 19:45 UTC, closed without merging