Statefull object
mate-academy/js_stateful-object pull request #471
Opened 2021-03-29 14:22 UTC by ivan-major

2021-03-30 10:22 UTC, vpolets requested changes, later dismissed

2021-03-30 10:22 UTC, vpolets commented on src/transformState.js
> +      }
ті ж зауваження що до наступного завдання

2021-03-30 12:54 UTC, ivan-major commented on src/transformState.js
> +      }
Добрий день.

Вніс зміни згідно ваших рекомендацій.
Маю надію, що краще як було напочатку.

Дякую.

2021-04-02 14:16 UTC, vkryvytskyy approved these changes

2021-04-02 14:16 UTC, vkryvytskyy commented on src/transformState.js
> +  for (const i of transforms) {
what does `i` means? give a meaningful name to the variable

2021-04-02 14:16 UTC, vkryvytskyy commented on src/transformState.js
> +        for (const k in i.properties) {
what does `k` means?

2021-04-02 14:16 UTC, vkryvytskyy approved these changes

2025-01-26 12:40 UTC, closed without merging