solution
mate-academy/js_stateful-object pull request #503
Opened 2021-04-22 15:33 UTC by ivan-shpynda

2021-04-22 18:00 UTC, leonid-vegera approved these changes
Good jobe!

2021-04-23 06:46 UTC, VinnieJ-2k20 requested changes
Let's rewrite the solution using `switch/case` structure.

2021-04-23 06:46 UTC, VinnieJ-2k20 commented on src/transformState.js
> +  for (const obj of transforms) {
```suggestion
  for (const transform of transforms) {
```

2021-04-23 06:46 UTC, VinnieJ-2k20 commented on src/transformState.js
> +    if (obj['operation'] === 'addProperties') {
```suggestion
    if (obj.operation === 'addProperties') {
```

2021-04-23 06:46 UTC, VinnieJ-2k20 commented on src/transformState.js
> +      Object.assign(state, obj['properties']);
```suggestion
      Object.assign(state, obj.properties);
```

2021-04-23 09:38 UTC, VinnieJ-2k20 requested changes
`switch/case` structure should always have default option in case of irregular inputs.
In this task it may do nothing, or throw an error.

2021-04-23 09:58 UTC, VinnieJ-2k20 approved these changes

2024-09-13 10:00 UTC, closed without merging