solution
mate-academy/js_stateful-object pull request #572
Opened 2021-06-22 16:21 UTC by vitaliy-martynyuk

2021-06-22 16:46 UTC, leonid1313 approved these changes

2021-06-22 17:50 UTC, solaryasha requested changes

2021-06-22 17:50 UTC, solaryasha commented on src/transformState.js
> +  for (let i = 0; i < actions.length; i++) {
Зручніше тут використати `for of`

2021-06-22 17:50 UTC, solaryasha commented on src/transformState.js
> +        }
Або можеш використати Object.assign

2021-06-22 17:50 UTC, solaryasha commented on src/transformState.js
> +      if (actions[i][firstLevelKey] === 'clear') {
Використай switch інструкцію

2021-06-22 18:50 UTC, vitaliy-martynyuk commented on src/transformState.js
> +      if (actions[i][firstLevelKey] === 'clear') {
використав для всіх значень, яких міг. там для clear просто не має ніяких додаткових об'єктів, тому я залишив йому один if

2021-06-23 10:14 UTC, solaryasha requested changes

2021-06-23 10:14 UTC, solaryasha commented on src/transformState.js
> +      if (item[firstLevelKey] === 'clear') {
Напиши switch інструкцію по типу action. Тоді, зможеш записати це через один `switch`

2021-06-23 11:05 UTC, solaryasha approved these changes
Good job !

2021-11-25 08:53 UTC, closed without merging