js_stateful-object
mate-academy/js_stateful-object pull request #68
Opened 2020-01-23 16:02 UTC by delenjer

2020-01-23 16:57 UTC, 8hokage requested changes

2020-01-23 16:57 UTC, earthhuman41 commented on src/transformState.js
> +        if (prop in state) {
проверяй через hasOwnProperty, ```in``` проверяет также в родительском объекте

2020-01-24 12:20 UTC, 8hokage requested changes

2020-01-24 12:20 UTC, earthhuman41 commented on src/transformState.js
> +        state.hasOwnProperty(prop);
зачем тебе эта строка?

2020-01-24 12:20 UTC, earthhuman41 commented on src/transformState.js
> +      Object.assign(state, transforms[i].properties);
вынеси в переменную transforms[i].properties, чтобы не писать много раз

2020-01-24 12:49 UTC, 8hokage approved these changes

2026-07-31 06:37 UTC, closed without merging