Task done
mate-academy/js_stateful-object pull request #706
Opened 2021-08-05 10:32 UTC by Virass

2021-08-05 11:04 UTC, alex-glotov67 approved these changes
Perfect solution!

2021-08-05 11:27 UTC, danheim requested changes
Gr

2021-08-05 11:27 UTC, danheim commented on src/transformState.js
> +  for (const key of actions) {
apples - apple
books - book
users - user
tables - table
actions - ?

```suggestion
  for (const key of actions) {
```

2021-08-05 11:27 UTC, danheim commented on src/transformState.js
> +        for (const arr of key.keysToRemove) {
this is not `arr`, this is key

2021-08-06 07:37 UTC, danheim approved these changes

2026-03-02 19:46 UTC, closed without merging