task complite
mate-academy/js_stateful-object pull request #829
Opened 2021-11-06 20:08 UTC by voronvasia

2021-11-08 13:44 UTC, vkryvytskyy requested changes

2021-11-08 13:44 UTC, vkryvytskyy commented on src/transformState.js
> +      }
Перебирай action.type через switch..case

2021-11-08 13:44 UTC, vkryvytskyy commented on src/transformState.js
> +      }
Тебе тут не нужен цикл `for (const obj in action) {`

2021-11-09 12:20 UTC, danylo-onishchuk approved these changes

2023-12-09 20:11 UTC, closed without merging