Solution
mate-academy/js_stateful-object pull request #831
Opened 2021-11-08 14:13 UTC by dariia-romanova

2021-11-08 18:01 UTC, WorkAccCom approved these changes
LGTM 🔥

2021-11-08 18:01 UTC, WorkAccCom commented on package.json
> +    "@mate-academy/scripts": "^0.9.7",
Please do not add useless files to your PR.
You can use **git add src/** command to add needed files
**git status** command — for checking file status

2021-11-09 09:04 UTC, AlinaMatuschak requested changes
Almost perfect 👍

2021-11-09 09:04 UTC, AlinaMatuschak commented on src/transformState.js
> +    if (action.type === 'addProperties') {
try use switch case when you want to check a value for multiple possible results

2021-11-09 13:25 UTC, AlinaMatuschak approved these changes
👌

2021-11-09 13:25 UTC, AlinaMatuschak commented on src/transformState.js
> +  for (const action of actions) {
```suggestion
  for (const action of actions) {
    const {type, extraData, keysToRemove} = action;
   
```

2021-11-09 13:25 UTC, AlinaMatuschak commented on src/transformState.js
> +        break;
it's last case, you can delete break

2021-11-09 14:35 UTC, AlinaMatuschak approved these changes

2023-11-19 15:48 UTC, closed without merging